### ISSUE TITLE
Exception when using compare action with a project which contains multiple Gerrit projects

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#101]
Exception message: Couldn't get [git log ..FETCH_HEAD] on repository [file:///code/4review/tools/idea]: Couldn't get [git log ..FETCH_HEAD] on repository [file:///code/4review/tools/idea]

Addition information: 
This exception was caused by right-click -> compare with branch

I suspect this happened because our project has a weird setup - essentially we have two separate project folders: tools/plugins and tools/idea. And the second project (tools/idea) references the first.

In this case, I opened the project under tools/idea but did a Compare with Branch for a project under the tools/plugins folder.

Plugin version: 0.8.1

Exception: 
```
git4idea.GitExecutionException: Couldn't get [git log ..FETCH_HEAD] on repository [file:///code/4review/tools/idea]
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil.loadCommitsToCompare(GerritGitUtil.java:338)
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil.loadCommitsToCompare(GerritGitUtil.java:347)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.CompareBranchAction.diffChange(CompareBranchAction.java:87)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.CompareBranchAction.access$000(CompareBranchAction.java:42)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.CompareBranchAction$1.call(CompareBranchAction.java:62)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.CompareBranchAction$1.call(CompareBranchAction.java:59)
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil$1.onSuccess(GerritGitUtil.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8$2.run(ProgressManagerImpl.java:407)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.openapi.vcs.VcsException: fatal: bad revision '..FETCH_HEAD'
 during executing git log ..FETCH_HEAD --pretty=format:%x01%H%x02%ct%x02%an%x02%at%x02%ae%x02%cn%x02%ce%x02%P%x02%s%x02%b%x02%B%x03 --encoding=UTF-8 --full-history --sparse -M --name-status --
    at git4idea.commands.GitSimpleHandler.run(GitSimpleHandler.java:238)
    at git4idea.history.GitHistoryUtils.loadDetails(GitHistoryUtils.java:804)
    at git4idea.history.GitHistoryUtils.history(GitHistoryUtils.java:771)
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil.loadCommitsToCompare(GerritGitUtil.java:334)
    ... 25 more
Caused by: com.intellij.openapi.vcs.VcsException: fatal: bad revision '..FETCH_HEAD'

    at git4idea.commands.GitSimpleHandler$1.processTerminated(GitSimpleHandler.java:224)
    at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:90)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:67)
    at com.sun.proxy.$Proxy85.processTerminated(Unknown Source)
    at git4idea.commands.GitTextHandler$1.processTerminated(GitTextHandler.java:79)
    at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
    at com.sun.proxy.$Proxy14.processTerminated(Unknown Source)
    at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:171)
    at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
    at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:153)
    at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:149)
    at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:133)
    at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:107)
    at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:91)
    at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:40)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

Recieved as exception report. Have not tried to reproduce it yet.

**Comment by lssilva** [comment]
I also have this issue 

Caused by: com.intellij.openapi.vcs.VcsException: fatal: bad revision '..FETCH_HEAD'

	at git4idea.commands.GitSimpleHandler$1.processTerminated(GitSimpleHandler.java:227)
	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy101.processTerminated(Unknown Source)
	at git4idea.commands.GitTextHandler$1.processTerminated(GitTextHandler.java:83)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy15.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:171)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:153)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:149)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:150)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:115)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:100)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 15.0.3  Build #IU-143.1821.5 
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_40-release 
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - VM: OpenJDK 64-Bit Server VM 
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - Vendor: JetBrains s.r.o 
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - OS: Mac OS X 
2016-03-22 10:10:54,427 [86373051]  ERROR - pplication.impl.LaterInvocator - Last Action: Gerrit.CompareBranch

**Comment by uwolfer** [comment]
@lssilva: What version of the Gerrit IntelliJ plugin do you have installed? Please make sure you have installed the most recent version. Do you also have a setup with multiple Git repos?

**Comment by lssilva** [comment]
Yes I read the bugs and they mentioned that it was fixed with the latest version I checked and I had the latest version. I tried opening only one project and it didn't work.
Actually no other operations worked for me, like view change etc..

**Comment by uwolfer** [comment]
> Actually no other operations worked for me, like view change etc..

I assume the list of changes does display changes, right?

Please also try if [these](https://github.com/uwolfer/gerrit-intellij-plugin#list-of-changes-is-empty) workarounds help in your case.
