### ISSUE TITLE
Retrieving changesets fail

### ISSUE THREAD

**Issue by BrandonSmith** [uwolfer/gerrit-intellij-plugin#120]
I can query and filter my gerrit instance. I see open and merged submissions.

However, I cannot retrieve changeset information. See error output below.
### Version Info

Android Studio 0.8.2
gerrit-intellij-plugin 0.9.2
Gerrit 2.9
### Event Log

11:25:34 PM Cannot show change: Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.
### Version Control Console

```
23:25:34.257: cd /Users/brandon/work/projects/android/rw/libs/republic-core/.git
23:25:34.257: git fetch --progress origin refs/changes/95/195/2
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.jetbrains.git4idea.ssh.SSHConfig.load(SSHConfig.java:124)
    at org.jetbrains.git4idea.ssh.SSHMain.<init>(SSHMain.java:121)
    at org.jetbrains.git4idea.ssh.SSHMain.parseArguments(SSHMain.java:483)
    at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:136)
```

**Comment by gdubicki** [comment]
Hey, this thing just happened to me too, while using plain InteliiJ IDEA, without your plugin.

I also have had a dangling `Host` line in my SSH config.

I'll paste my error message for searchability of this ticket as apparently JetBrains haven't made the error message more user-friendly in the last 2 years. 👎 

My full error while trying to push to a remote repo was:

```
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.jetbrains.git4idea.ssh.SSHConfig.load(SSHConfig.java:124)
    at org.jetbrains.git4idea.ssh.SSHMain.<init>(SSHMain.java:121)
    at org.jetbrains.git4idea.ssh.SSHMain.parseArguments(SSHMain.java:498)
    at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:136)
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
