### ISSUE TITLE
Exception "Cannot handle commit here"

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#122]
Got this exception as exception report.

Just pressed Refresh button in Gerrit tab window and got this message.

Plugin version: 0.9.2

``
java.lang.IllegalArgumentException: Cannot handle commit here: '6b1d4a7c864bc98b78d9dab3b7f57b66d8f65f11'.
    at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitMessageFormatter.getParentLine(CommitMessageFormatter.java:88)
    at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitMessageFormatter.getLongCommitMessage(CommitMessageFormatter.java:69)
    at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.ChangesWithCommitMessageProvider.getChangesWithCommitMessage(ChangesWithCommitMessageProvider.java:57)
    at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.ChangesWithCommitMessageProvider.provide(ChangesWithCommitMessageProvider.java:51)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:203)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:176)
    at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:114)
    at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:99)
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil$1.onSuccess(GerritGitUtil.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8$2.run(ProgressManagerImpl.java:407)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
``

**Comment by uwolfer** [comment]
Exception message: Cannot handle commit here: 'bd8823625217dafdc3c50ba3344916f7a935fcaa'; got 0 parents.

Plugin version: 0.9.5.2

IntelliJ version: IntelliJ IDEA 14.0.3 IC-139.1117

Exception:
```
java.lang.IllegalArgumentException: Cannot handle commit here: 'bd8823625217dafdc3c50ba3344916f7a935fcaa'; got 0 parents.
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitMessageFormatter.getParentLine(CommitMessageFormatter.java:89)
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitMessageFormatter.getLongCommitMessage(CommitMessageFormatter.java:70)
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.ChangesWithCommitMessageProvider.getChangesWithCommitMessage(ChangesWithCommitMessageProvider.java:57)
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.ChangesWithCommitMessageProvider.provide(ChangesWithCommitMessageProvider.java:51)
```
