### ISSUE TITLE
Pool timeout when connecting to gerrit

### ISSUE THREAD

**Issue by Lajcik** [uwolfer/gerrit-intellij-plugin#148]
I have trouble establishing a connection to gerrit on Intellij 14.0.3 via HTTPS. I keep getting 
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool. Everything's fine on IDEA 13.

Here's the important parts of the stacktrace:

java.lang.RuntimeException: com.google.gerrit.extensions.restapi.RestApiException: Request failed.
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.doAccessToGerritWithModalProgress(GerritUtil.java:129)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.accessToGerritWithModalProgress(GerritUtil.java:98)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.checkCredentials(GerritUtil.java:537)
	at com.urswolfer.intellij.plugin.gerrit.ui.SettingsPanel$1.actionPerformed(SettingsPanel.java:79)
(...CUT...)
Caused by: com.google.gerrit.extensions.restapi.RestApiException: Request failed.
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:134)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.getRequest(GerritRestClient.java:98)
	at com.urswolfer.gerrit.client.rest.http.accounts.AccountApiRestClient.get(AccountApiRestClient.java:45)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.testConnection(GerritUtil.java:509)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.access$300(GerritUtil.java:70)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$16.compute(GerritUtil.java:541)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$16.compute(GerritUtil.java:537)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$1.run(GerritUtil.java:119)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:422)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:641)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:250)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:227)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:173)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.urswolfer.intellij.plugin.gerrit.rest.SslSupport.execute(SslSupport.java:75)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.doRest(GerritRestClient.java:176)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:119)
	... 22 more

**Comment by uwolfer** [comment]
Do you also get this error when you press the test-button in plugin settings?

**Comment by Lajcik** [comment]
Yes

**Comment by uwolfer** [comment]
It looks like connections are leaked. This could also be done by another part of the IDE / plugin.

Please try:
* restart your IDE and try again
* disable other inofficial plugins (just to ensure that no other plugin leaks connections)

**Comment by Lajcik** [comment]
The only unofficial plugin I had was BashSupport but disabling it doesn't help. Restarting obviously doesn't help.

I'll try a fresh install when I have time and report back. I don't know when I'll have time for that - being at work :)

Thanks for your replies.

**Comment by uwolfer** [comment]
I don't think a fresh install will help. You could try to connect to gerrit-review.googlesource.com (without user / pw) to check if your issue is host specific.

Probably it just fails with your gerrit server and does not cleanup connections.

**Comment by Lajcik** [comment]
Strange thing 

I changed to gerrit-review.googlesource.com and it worked. Changed back to our local gerrit server and now it also works. Magic stuff. Thanks for your time.

**Comment by uwolfer** [comment]
Sounds really strange. Please keep an eye on it and report back when you can reproduce this issue again. I would like to get it fixed.
