### ISSUE TITLE
IntelliJ sends timestamp to Gerrit REST API in wrong format

### ISSUE THREAD

**Issue by stanislavb** [uwolfer/gerrit-intellij-plugin#151]
Hello.

We're tinkering with Gerrit 2.10 and intellij integration. We currently only have the download-commands plugin installed on Gerrit. IntelliJ seems to send timestamps in a format not expected by Gerrit. Do you have any idea where to look for the problem?

Nginx access.log
```
https://gerrit.example.net:443/a/changes/project-trial~develop~I1794ed874f8fd615d79afeee449aebdfae6f1c5b/revisions/2ff09d932a15843119e999b279c8e8631ee42b5b/review- 192.168.205.112:- "POST /a/changes/project-trial~develop~I1794ed874f8fd615d79afeee449aebdfae6f1c5b/revisions/2ff09d932a15843119e999b279c8e8631ee42b5b/review HTTP/1.1" 0.065 1109:372 500 "-" "gerrit-intellij-plugin/0.9.5.2 using gerrit-rest-java-client/0.8.2 using Apache-HttpClient/4.3.2 (java 1.5)" "-"
```

Gerrit error_log
```
[2015-03-03 15:15:12,588] ERROR com.google.gerrit.httpd.restapi.RestApiServlet : Error in POST /a/changes/project-trial~develop~I1794ed874f8fd615d79afeee449aebdfae6f1c5b/revisions/2ff09d932a15843119e999b279c8e8631ee42b5b/review
java.lang.IllegalArgumentException: Expected date and optional time: Mar 3, 2015 3:14:16 PM
	at com.google.gwtjsonrpc.common.JavaSqlTimestampHelper.parseTimestamp(JavaSqlTimestampHelper.java:37)
	at com.google.gwtjsonrpc.server.SqlTimestampDeserializer.deserialize(SqlTimestampDeserializer.java:50)
	at com.google.gwtjsonrpc.server.SqlTimestampDeserializer.deserialize(SqlTimestampDeserializer.java:31)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:59)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gerrit.httpd.restapi.RestApiServlet.parseRequest(RestApiServlet.java:490)
	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:303)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:279)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:269)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.gerrit.httpd.RequireIdentifiedUserFilter.doFilter(RequireIdentifiedUserFilter.java:55)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:113)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:68)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.ProjectDigestFilter.doFilter(ProjectDigestFilter.java:107)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
	at org.eclipse.jetty.server.Server.handle(Server.java:461)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by uwolfer** [comment]
@stanislavb: What are you doing when you get this action (I see you are doing a review - but please post any options you have selected)?

**Comment by uwolfer** [comment]
Fixed: https://github.com/uwolfer/gerrit-rest-java-client/commit/3e119670648bffda002ec9da6969be2138acb61c

Will be included in next release.
