### ISSUE TITLE
push dialog does not appear intellij version 14.1 latest plugin

### ISSUE THREAD

**Issue by igreenfield** [uwolfer/gerrit-intellij-plugin#157]
2015-03-25 13:12:43,287 [  69676]  ERROR - llij.ide.plugins.PluginManager - git4idea.push.GitPushTargetPanel.<init>(Lgit4idea/repo/GitRepository;Lgit4idea/push/GitPushTarget;)V 
java.lang.NoSuchMethodError: git4idea.push.GitPushTargetPanel.<init>(Lgit4idea/repo/GitRepository;Lgit4idea/push/GitPushTarget;)V
	at com.urswolfer.intellij.plugin.gerrit.push.GerritPushTargetPanel.<init>(GerritPushTargetPanel.java:39)
	at git4idea.push.GitPushSupport.createTargetPanel(GitPushSupport.java)
	at git4idea.push.GitPushSupport.createTargetPanel(GitPushSupport.java:40)
	at com.intellij.dvcs.push.PushController.a(PushController.java:237)
	at com.intellij.dvcs.push.PushController.a(PushController.java:205)
	at com.intellij.dvcs.push.PushController.<init>(PushController.java:89)
	at com.intellij.dvcs.push.ui.VcsPushDialog.<init>(VcsPushDialog.java:56)
	at com.intellij.dvcs.push.VcsPushAction.actionPerformed(VcsPushAction.java:45)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-03-25 13:12:43,292 [  69681]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1  Build #IU-141.177.4

**Comment by ihorpts** [comment]
Seems to be I have the same issue in 14.1 version ...

**Comment by uwolfer** [comment]
I can confirm it. Will look into it ASAP.

**Comment by uwolfer** [comment]
I have just released an update for 14.1. Please update (you probably need to check for updates manually in IntelliJ plugin settings).

**Comment by ihorpts** [comment]
@uwolfer thank you for the quick fix!
