### ISSUE TITLE
Add Reviewer takes a long time

### ISSUE THREAD

**Issue by yairogen** [uwolfer/gerrit-intellij-plugin#180]
when adding a reviewer it take a long long time until it finds that reviewer from all users - even when supplying an exact user id.
When we start typing the user id we only see first characters (although we typed them all) and it takes a long time until it shows all the characters we typed and then there is a match.

**Comment by uwolfer** [comment]
@yairogen: Does this action work faster in Gerrit web UI?

**Comment by yairogen** [comment]
Yes, in the ui it’s very fast.

**Comment by uwolfer** [comment]
@yairogen: Does the IntelliJ UI completely hang while typing or is it still responsive?

**Comment by yairogen** [comment]
It hangs.

Regards,

Yair Ogen

**Comment by uwolfer** [comment]
I have just tried to reproduce this issue with a quite large Gerrit installation (gerrit-review.googlesource.com). I'm not able to reproduce it there with IntelliJ IDEA 14.1. It hangs sometimes a little bit (<1s), but it is usable.

Can you please provide some more details:
* how long does it hang?
* how many user accounts does your installation have?
* version of Gerrit?
* version of IntelliJ?

Thank you.

**Comment by uwolfer** [comment]
@yairogen: If you still can reproduce this issue, please post feedback to my questions above. Thanks.

**Comment by yairogen** [comment]
@uwolfer. Actually now it's completely broken. fails on NPE:

2015-10-11 09:38:31,960 [234309423]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.c(EditorTextFieldProviderImpl.java:68)
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.createEditor(EditorTextFieldProviderImpl.java:56)
	at com.intellij.ui.EditorTextField.b(EditorTextField.java:367)
	at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:352)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at javax.swing.JRootPane.addNotify(JRootPane.java:757)
	at java.awt.Container.addNotify(Container.java:2773)
	at java.awt.Window.addNotify(Window.java:770)
	at java.awt.Dialog.addNotify(Dialog.java:760)
	at java.awt.Window.pack(Window.java:807)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:675)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:463)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1637)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1586)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.AddReviewersAction.actionPerformed(AddReviewersAction.java:77)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.AddReviewersAction$Proxy.actionPerformed(AddReviewersAction.java:193)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-10-11 09:38:31,964 [234309427]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA (Minerva) IU-143.116.4  Build #IU-143.116.4 
2015-10-11 09:38:31,964 [234309427]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_60 
2015-10-11 09:38:31,964 [234309427]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) Server VM 
2015-10-11 09:38:31,965 [234309428]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-10-11 09:38:31,965 [234309428]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2015-10-11 09:38:31,965 [234309428]  ERROR - llij.ide.plugins.PluginManager - Last Action: Gerrit.AddReviewers 
2015-10-11 09:38:39,112 [234316575]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.c(EditorTextFieldProviderImpl.java:68)
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.createEditor(EditorTextFieldProviderImpl.java:56)
	at com.intellij.ui.EditorTextField.b(EditorTextField.java:367)
	at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:352)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at javax.swing.JRootPane.addNotify(JRootPane.java:757)
	at java.awt.Container.addNotify(Container.java:2773)
	at java.awt.Window.addNotify(Window.java:770)
	at java.awt.Dialog.addNotify(Dialog.java:760)
	at java.awt.Window.pack(Window.java:807)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:675)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:463)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1637)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1586)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.AddReviewersAction.actionPerformed(AddReviewersAction.java:77)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.AddReviewersAction$Proxy.actionPerformed(AddReviewersAction.java:193)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-10-11 09:38:39,112 [234316575]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA (Minerva) IU-143.116.4  Build #IU-143.116.4 
2015-10-11 09:38:39,113 [234316576]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_60 
2015-10-11 09:38:39,113 [234316576]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) Server VM 
2015-10-11 09:38:39,113 [234316576]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-10-11 09:38:39,114 [234316577]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2015-10-11 09:38:39,114 [234316577]  ERROR - llij.ide.plugins.PluginManager - Last Action: Gerrit.AddReviewers

**Comment by uwolfer** [comment]
@yairogen: Since you are using the lasted EAP, I have also tried to reproduce this NPE. I'm not able to reproduce it (trace looks like an IntelliJ internal NPE). I assume you have installed the latest version of the plugin.

**Comment by yairogen** [comment]
Using default updates not manual. What's the latest plug-in version?

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by uwolfer** [comment]
@yairogen: If the plugin settings do not show an update, you are using the latest version.

**Comment by uwolfer** [comment]
Please reopen if you still can reproduce this issue.
