### ISSUE TITLE
NullPointerException error 

### ISSUE THREAD

**Issue by RaymondCQ** [uwolfer/gerrit-intellij-plugin#184]
IntelliJ 14.1.3
Gerrit plugin version: 0.9.7.1-141

null
java.lang.NullPointerException
	at com.urswolfer.intellij.plugin.gerrit.extension.GerritCheckoutProvider.getCloneBaseUrl(GerritCheckoutProvider.java:160)
	at com.urswolfer.intellij.plugin.gerrit.extension.GerritCheckoutProvider.doCheckout(GerritCheckoutProvider.java:109)
	at com.urswolfer.intellij.plugin.gerrit.extension.GerritCheckoutProvider$Proxy.doCheckout(GerritCheckoutProvider.java:214)
	at com.intellij.openapi.vcs.checkout.CheckoutAction.actionPerformed(CheckoutAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by uwolfer** [comment]
Already fixed in https://github.com/uwolfer/gerrit-intellij-plugin/commit/035e6181162e801444d9ca2ba57f331b4d2b3a93.

Will be included in the next release.

**Comment by RaymondCQ** [comment]
Thanks a lot, when the next release will be published ? Any workaround at this moment ?

**Comment by uwolfer** [comment]
I have just released a new version - if you do not get a notification, please refresh the plugin list in IntelliJ settings manually and update the plugin.

**Comment by RaymondCQ** [comment]
I have installed the new plugin, it works, appreciate it.

Now I am facing another issue, can't push the change to gerrit through plugin, it is getting error "Push failed: Failed with error: fatal: Could not read from remote repository.", however I can push the change in command line. 

Below is the config file of git (.git/config)
*******************************************
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = ssh://username@hostname:29418/Demo
	fetch = +refs/heads/*:refs/remotes/origin/*
        push = refs/heads/master:refs/for/master
[branch "master"]
	remote = origin
	merge = refs/heads/master
*********************************************

Any thing wrong ? sorry I am new to gerrit.

![image](https://cloud.githubusercontent.com/assets/13316962/9466613/afd76c94-4b68-11e5-86c6-d33dbc8be2ea.png)

**Comment by RaymondCQ** [comment]
![image](https://cloud.githubusercontent.com/assets/13316962/9466665/1ebd5a4c-4b69-11e5-9a29-4893a171b511.png)

**Comment by RaymondCQ** [comment]
![image](https://cloud.githubusercontent.com/assets/13316962/9466800/ed499466-4b69-11e5-94cd-7e64d82b51ee.png)

**Comment by uwolfer** [comment]
@RaymondCQ: Can you please provide the full (anonymized) error which you can find in IntelliJ "Version Control"-tab log?

**Comment by RaymondCQ** [comment]
![image](https://cloud.githubusercontent.com/assets/13316962/9488559/8ab0f782-4c0d-11e5-86a4-45601c4e1617.png)

![image](https://cloud.githubusercontent.com/assets/13316962/9488578/a14de95a-4c0d-11e5-8221-a28806140c84.png)

![image](https://cloud.githubusercontent.com/assets/13316962/9488647/fa85cc5e-4c0d-11e5-9b03-3fa0e950bd9f.png)

This is the error log and gerrit setting, please kindly help check, thanks.

**Comment by uwolfer** [comment]
In the 2nd screenshot you can see a message "Authentication failed". Please check your IntelliJ Git settings. There you can choose between "Built-in" and "Native" SSH. Please try both settings.
