### ISSUE TITLE
NullPointerException in GerritChangeListPanel#generateColumnsInfo (was: doesn't start in idea 14.1.4)

### ISSUE THREAD

**Issue by undersky76** [uwolfer/gerrit-intellij-plugin#187]
idea : 14.1.4
Gerrit : 2.10
Plugin : 0.9.7.2-141
JVM : 1.8.0_40

```
java.lang.NullPointerException
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.generateColumnsInfo(GerritChangeListPanel.java:245)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.initModel(GerritChangeListPanel.java:220)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.setChanges(GerritChangeListPanel.java:204)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel$2.consume(GerritChangeListPanel.java:136)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel$2.consume(GerritChangeListPanel.java:133)
	at com.urswolfer.intellij.plugin.gerrit.rest.LoadChangesProxy$1.consume(LoadChangesProxy.java:74)
	at com.urswolfer.intellij.plugin.gerrit.rest.LoadChangesProxy$1.consume(LoadChangesProxy.java:63)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$18$1$1.run(GerritUtil.java:620)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
Is the Gerrit instance you get this failure with available in the public so I could try it also? You could probably try to connect to another Gerrit instance (e.g. gerrit-review.googlesource.com) in order to see if the issue only exists with your installation.
