### ISSUE TITLE
NoSuchElementException when diffing changes

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#188]
(Received as exception report)

I pushed 2 amended commits, error occur when I check "Diff agains:Base" to "Diff against: 1"

Plugin version: 0.9.7.2-141

IntelliJ version: IntelliJ IDEA 14.1.4 IC-141.1532

Exception: 
```
java.util.NoSuchElementException
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
	at com.google.common.collect.Iterators.find(Iterators.java:712)
	at com.google.common.collect.Iterables.find(Iterables.java:646)
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitDiffBuilder.buildCommitMsgChange(CommitDiffBuilder.java:83)
	at com.urswolfer.intellij.plugin.gerrit.ui.changesbrowser.CommitDiffBuilder.getDiff(CommitDiffBuilder.java:78)
	at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:184)
	at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:173)
	at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:114)
	at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:99)
	at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil$1.onSuccess(GerritGitUtil.java:131)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1$2.run(ProgressManagerImpl.java:153)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
Comment from another exception-report:
Compare a Gerrit change which another patch version instead of base.

**Comment by uwolfer** [comment]
I am still not able to reproduce this exception. If anybody can reproduce it, please provide more information.

**Comment by david-hatton** [comment]
I am consistently seeing it, but I don't know what additional details you need.

For a Gerrit review with multiple commits, trying to view diff against anything other than "Base" results in the exception as reported. Please let me know what information you require.

**Comment by uwolfer** [comment]
@david-hatton: Probably following question help me to isolate this issue:
 1. What OS are you using?
 2. IntelliJ version?
 3. Can you reproduce this issue also for commits which you have pushed by yourself (and all revisions you are comparing are locally available)?
 4. Do you know any colleagues who are working on the same problem and can reproduce this issue also / cannot reproduce it?
 5. Does this issue occur since the begin of the time you are using this plugin?

**Comment by ihorpts** [comment]
hi @uwolfer 

I face the same issue when I want to see changes against different change sets.
My setup:
1. Windows 7 Professions (service pack 1)
2. IntelliJ IDEA 15 (Build #IU 143-381)
3. Didn't check it yet
4. -
5. I found it out by starting to use IDEA 15 (issue might occur earlier)

Here are few screenshots with step descriptions:
1. Start to do a code review against base change set:
![gerrit_issue_1](https://cloud.githubusercontent.com/assets/7080319/11116020/c05f7cb4-892f-11e5-9e8b-7f30fe1ab024.jpg)

2. Switch to another change set
![gerrit_issue_2](https://cloud.githubusercontent.com/assets/7080319/11116023/c8602b3e-892f-11e5-8b1a-f5169c4ecb9c.jpg)

3. An error appears
![gerrit_issue_3](https://cloud.githubusercontent.com/assets/7080319/11116025/ce1adce0-892f-11e5-8c09-9d68c58b882c.jpg)

**Comment by uwolfer** [comment]
@ihorpts: Thank you very much. In screenshot 1, when you do not change base, is there COMMIT_MSG visible in the diff tree?

**Comment by david-hatton** [comment]
1. Windows 7 Enterprise Edition
2. IntelliJ 15.0 (Build #IC-143.381)
3. Yes (but see 3a below)
4. None of my colleagues use the plug-in. I can ask them to try if you need more info.
5. This problem only started since I upgraded to IJ 15.0 (and subsequently upgraded the plugin). It never occurred on IJ 14.x.

3a. One thing to note might be how we use the gerrit process. We use amended commits as part of the process, so an author would do the following::

A. Make Changes, Commit to Branch
> git add, git commit
B. Submit to gerrit
> git push origin HEAD:refs/for/master
C. Make further changes, amend original commit
> git add, git commit --amend
D. Re-submit to gerrit
> git push origin HEAD:refs/for/master

And I see the same as @ihorpts. And when comparing to "base" I do see a COMMIT_MSG.

**Comment by uwolfer** [comment]
@david-hatton: Thanks! I do not think that you workflow is related to this issue - I use it exactly the same way.

Since both of you @david-hatton and @ihorpts are using Windows and the code related to this issue does some file operations, I think it could be related to that. I will try to reproduce this issue on a Win setup.

**Comment by ihorpts** [comment]
@uwolfer 
>>In screenshot 1, when you do not change base, is there COMMIT_MSG visible in the diff tree?
Yes, it's visible there

**Comment by uwolfer** [comment]
I have just released a new version which contains this fix. Thanks again for your feedback - without that I would not have been able to fix it.

**Comment by david-hatton** [comment]
Thank you @uwolfer!!!

Great plugin by the way!!

**Comment by ihorpts** [comment]
Thanks @uwolfer for the quick fix!
Works now...
