### ISSUE TITLE
NullPointerException in IDEA 15.0.2 after some time

### ISSUE THREAD

**Issue by zeratul021** [uwolfer/gerrit-intellij-plugin#195]
Hello,

after returning to IntelliJ IDEA (from suspend or overnight locked computer) the plugin fails with NPEs and IDE restart is required to fix it. Windows and Linux alike.

(Might be imagining this but I think this problem existed in IntelliJ IDEA 14 in the beginning as well but was fixed later on).

```
null
java.lang.NullPointerException
	at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$3.consume(RepositoryChangesBrowserProvider.java:145)
	at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$3.consume(RepositoryChangesBrowserProvider.java:142)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$18$1$1.run(GerritUtil.java:620)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by uwolfer** [comment]
@zeratul021: This trace looks really strange. but I have received some others which look like quite equal via exception reports. It looks like the change cannot be read on your Gerrit server anymore.

Could it be that you have lost your Gerrit session? Do other operations like refreshing the change list still work?

**Comment by zeratul021** [comment]
@uwolfer IIRC the refreshing and filtering didn't work as well. I can try to let it sleep tomorrow evening and play around Friday morning.

**Comment by sjelen** [comment]
@uwolfer Hi, I have the same issue. It happens after some time of inactivity, when presumably the Gerrit session times out. I can filter the waiting code reviews, but when I select one of them to display the diff I get a null pointer instead. Interestingly enough, Intellij doesn't ask to unlock it's password store in these cases.

**Comment by uwolfer** [comment]
@sjelen: Just to ensure that I correctly understand your issue: you can see in the list of changes all your changes (even after a refresh), but when you select it, it fails with an error?

**Comment by sjelen** [comment]
@uwolfer I can apply the "Reviewer: Me" filter, and list of reviews assigned to me is correctly shown. The diff windows shows the diff from the last selected code review, which is outdated. Nothing is selected in the list of changes for review. When I select one of the changes, I get the NPE.

**Comment by uwolfer** [comment]
@sjelen and @zeratul021: What's the version of the Gerrit server you are connected to?

**Comment by sjelen** [comment]
@uwolfer Gerrit version is 2.8.1

**Comment by uwolfer** [comment]
@zeratul021: Can you please also answer my questions above? Probably we can find some commonalities.

**Comment by zeratul021** [comment]
@uwolfer sorry I didn't reply before, we are on the same team = same environments. Unfortunately I was not able to reproduce this again. I keep IDEA running during night, I'll see in the morning.

**Comment by zeratul021** [comment]
I clicked refresh today and when I tried to select any of the changes I got NPE. Filters do work, the information panel below updates (change-id, author...) but the diff panel doesn't change.

```
null
java.lang.NullPointerException
	at com.urswolfer.intellij.plugin.gerrit.ui.diff.CommentsDiffTool$3.consume(CommentsDiffTool.java:156)
	at com.urswolfer.intellij.plugin.gerrit.ui.diff.CommentsDiffTool$3.consume(CommentsDiffTool.java:153)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$18$1$1.run(GerritUtil.java:620)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by uwolfer** [comment]
If you have admin access, I suggest you to try to set a higher `web_sessions` timeout (see https://gerrit-review.googlesource.com/Documentation/config-gerrit.html or https://code.google.com/p/gerrit/issues/detail?id=781). If it does not happen anymore then, we know that this issue is because of the login caching mechanism.

Also, I suggest updating to a more recent version of Gerrit (not just because of this issue). It should not be that hard to update.

**Comment by zeratul021** [comment]
Thanks - I will speak to our DevOps/Infra team and see what can be done.

**Comment by zeratul021** [comment]
@uwolfer so the issue seems to be gone after Gerrit upgrade to 2.11.5
