### ISSUE TITLE
NoSuchElementException (when loading change)

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#203]
Addition information: 
This happens after 16 hours without shutting down IntelliJ and trying to fetch new gerrit changes. It first doesn't show changes (empty list) and after changing the filter (selecting different Owner in the list) it throws this exception.

Plugin version: 0.9.7.6-142

IntelliJ version: IntelliJ IDEA 15.0.2 IU-143.1184

OS: Linux 3.13.0-79-generic

Java: Oracle Corporation 1.8.0_74

Exception:

```
java.util.NoSuchElementException
    at java.util.ArrayList$Itr.next(ArrayList.java:854)
    at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:297)
    at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:289)
    at com.urswolfer.gerrit.client.rest.http.changes.ChangeApiRestClient.get(ChangeApiRestClient.java:158)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$12.get(GerritUtil.java:401)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$12.get(GerritUtil.java:390)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$18$1.run(GerritUtil.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

(Received as exception report.)

**Comment by uwolfer** [comment]
This is most probably because of an expired session.

As a workaround, IntelliJ can be restarted when login expired or [Gerrit server config](https://gerrit-review.googlesource.com/Documentation/config-gerrit.html) can be changed (`web_sessions` cache).

**Comment by uwolfer** [comment]
Since I'm not able to reproduce this issue, it would be really helpful if somebody who can reproduce it could contact me / post feedback here.

**Comment by venth** [comment]
I can reproduce this issue - I believe. Reproduction path:
* open IntelliJ with access to internal network where dns name for gerrit server will be resolved
* open a change set
* suspend machine
* change network environment so that there is no way to resolve gerrit server dns anymore
* open new project inside IntelliJ - there you are.

For me only solution is to reopen project once I'm in office.

**Comment by uwolfer** [comment]
If you can reach your sys admin, you could try to extend session expiration time:

```
[cache "web_sessions"]
    maxAge = 1 y
```

https://gerrit-review.googlesource.com/Documentation/config-gerrit.html

If you can change this, please let me know if this fixes your issue. In that case, I need to improve session expiration detection in the plugin.

**Comment by sschuberth** [comment]
I'm not sure whether it's related, but it seems there's a bug in Gerrit that makes sessions timeout prematurely, see the discussion at https://groups.google.com/d/topic/repo-discuss/Vk6UeWRHx0A/discussion.

**Comment by uwolfer** [comment]
Questions for everyone who can reproduce this issue:

1. Are you using a HTTP password set in Gerrit web UI settings?
2. If not, can you please try to do so and use these credentials? Does that help?

**Comment by uwolfer** [comment]
Fixed in one of the last releases (fix included in gerrit-rest-java-client).
