### ISSUE TITLE
NullPointerException: SystemDefaultRoutePlanner#determineProxy

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#219]
I often receive this exception reports (which is not directly inside the code of this plugin). I'm not able to reproduce it - any steps to reproduce are very welcome.

Details from a user:

> I get this message every time I start IntelliJ for a while now I think I had the same issue in IntelliJ 11 as well but I have not submitted a report.
> There is an error message during the project load but afterwards everything works fine.
> I do not have setup a proxy in IntelliJ.

Plugin version: 0.9.8.1-142
IntelliJ version: IntelliJ IDEA 2016.1.2 IU-145.972
OS: Windows 7 6.1
Java: Oracle Corporation 1.8.0_77

Exception:

```
java.lang.NullPointerException
    at org.apache.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:79)
    at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:77)
    at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at com.urswolfer.gerrit.client.rest.http.HttpRequestExecutor.execute(HttpRequestExecutor.java:34)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.tryGerritHttpAuth(GerritRestClient.java:299)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.updateGerritAuth(GerritRestClient.java:254)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.updateGerritAuthWhenRequired(GerritRestClient.java:248)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:182)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:163)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:155)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:132)
    at com.urswolfer.gerrit.client.rest.http.GerritRestClient.getRequest(GerritRestClient.java:101)
    at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.get(ChangesRestClient.java:97)
    at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.access$000(ChangesRestClient.java:34)
    at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient$1.get(ChangesRestClient.java:62)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$11.get(GerritUtil.java:320)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$11.get(GerritUtil.java:316)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20$1.run(GerritUtil.java:685)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by uwolfer** [comment]
Closing as I've not received this exception anymore for a longer time (no reports with IntelliJ > 2018.1.6).
