### ISSUE TITLE
List of changes is empty, no errors in the log file.  IntelliJ 2016.1.3

### ISSUE THREAD

**Issue by gkrasnow** [uwolfer/gerrit-intellij-plugin#222]
I am noticing that on occasion the list of changes in the gerrit plugin is empty.  I have found that the only way to once again show the list of changes is to quit and restart IntelliJ.  I tried looking for errors in the IntelliJ log file but did not find any.  I am not 100% sure, but it may be related to re-starting of the gerrit server.  Is it possible that the plugin gets confused and cannot establish a new session if the old session has disappeared?

**Comment by uwolfer** [comment]
@gkrasnow: Yes, it is very possible that this is because of Gerrit server restarts. Once the server restarts, the server does not recognize the session anymore and it is handled as anonymous user. In your setup, most probably anonymous users are not allowed to view changes.

Please try this when this situation occurs again: type `owner:self` into the filter field and press enter. Then post the error message you get.

**Comment by gkrasnow** [comment]
Seems that adding the owner:self may forced it to try to establish a new session.  At least it pulled up the list of changes.  However, the changes themselves are still not refreshing and I see this in the log file:

```
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2016.1.3  Build #IU-145.1617.8 
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_76-release 
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - VM: OpenJDK 64-Bit Server VM 
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - Vendor: JetBrains s.r.o 
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X 
2016-06-28 07:37:28,861 [667428233]  ERROR - plication.impl.ApplicationImpl - Last Action: Gerrit.Refresh 
2016-06-28 07:37:30,837 [667430209]  ERROR - plication.impl.ApplicationImpl - null 
java.util.NoSuchElementException
    at java.util.ArrayList$Itr.next(ArrayList.java:854)
    at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:297)
    at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:289)
    at com.urswolfer.gerrit.client.rest.http.changes.ChangeApiRestClient.get(ChangeApiRestClient.java:183)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$14.get(GerritUtil.java:451)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$14.get(GerritUtil.java:440)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20$1.run(GerritUtil.java:685)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by uwolfer** [comment]
Probably related to #203 and #178.

**Comment by tgrip** [comment]
I have the same problem since updating IntelliJ. 

When I change the filter I'm getting the following error message: Request not successful. Message: Forbidden. Status-Code: 403. Content: Must be signed-in to use owner:self.
The test connections from the setting is working well.

**Comment by uwolfer** [comment]
@tgrip: Can you also reproduce this issue after restarting IntelliJ?

**Comment by tgrip** [comment]
Yeah, same problem after restarting IntelliJ

**Comment by uwolfer** [comment]
@tgrip: Please check the plugin settings if your credentials are still available. It looks like to plugin tries to request data without your credentials. If they are still entered, please try to remove and re-enter them.

**Comment by tgrip** [comment]
Removing and adding again the credentials didn't help. The Gerrit plugin still works with 2016.1.2 version.

When I removed my credentials and put them again, an IntelliJ error was sent, which said something about credentials sending. Unfortunately I can not find the bug report again.

We have Gerrit version v2.9.3

**Comment by tgrip** [comment]
Is there any update on this?

**Comment by uwolfer** [comment]
@tgrip: Unfortunately not...

How do you login when you use Gerrit in your browser? HTTP auth? Or some single sign on solution?

**Comment by tgrip** [comment]
i'm connecting with HTTP auth. When I use the test button in the settings, it works

**Comment by tgrip** [comment]
It is working now. The problem was with the password saving in IntelliJ. It probably didn't send then the password right to Gerrit or something along these lines
