### ISSUE TITLE
NoSuchMethodError on upgrade to IntelliJ 2016.2

### ISSUE THREAD

**Issue by colinsmcintyre** [uwolfer/gerrit-intellij-plugin#231]
I've just this morning updated to IntelliJ IDEA 2016.2 Ultimate and I'm getting an error.

Opening the IDE, I get the popup to say there are changes waiting for my review, but when I open the Gerrit tab, I get this:

```
NoSuchMethodError: com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;
```

I presume this is just a version mismatch between the plugin and the IDE, but the "Update Plugin" option is disabled suggesting I have the latest version.  Is there a planned update for the plugin to support 2016.2?

OS: Windows 7
Plugin version: 0.9.8-142
IntelliJ version: 
IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

Here's the full stacktrace of the error:

```
com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;
java.lang.NoSuchMethodError: com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider.get(RepositoryChangesBrowserProvider.java:87)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.createToolWindowContent(GerritToolWindow.java:71)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindowFactory.createToolWindowContent(GerritToolWindowFactory.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:568)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$9.run(ToolWindowManagerImpl.java:550)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by colinsmcintyre** [comment]
Or if I'd managed to search correctly, I'd have found [https://github.com/uwolfer/gerrit-intellij-plugin/issues/210](https://github.com/uwolfer/gerrit-intellij-plugin/issues/210) which pointed me to the latest version.  I had to install manually

**Comment by uwolfer** [comment]
@colinsmcintyre: Have you uninstalled and then reinstalled the plugin in plugin settings? Or have you just manually refreshed the plugin list and then selected the update option?

**Comment by colinsmcintyre** [comment]
@uwolfer I tried refreshing the plugin list but the update option was always disabled, even after restarting IntelliJ.  I didn't uninstall, I just chose "Install plugin from disk..." and that seemed to be enough for it to update

**Comment by uwolfer** [comment]
@colinsmcintyre: I have just pushed a new release. Can you please refresh the plugin list in IntelliJ settings and check if the new update is displayed? If not, please uninstall the plugin and reinstall it. Can you please let me know which way worked out for you? It's possible that IntelliJ does not display updates anymore since you have installed it manually from disk.

**Comment by colinsmcintyre** [comment]
@uwolfer I just opened IntelliJ this morning and got this event popup (no need to refresh the plugin list):

![capture](https://cloud.githubusercontent.com/assets/9606531/16865702/c38c6e9c-4a5e-11e6-8e8b-090dad5f7799.PNG)

This takes me from v0.9.8.1-146 (the version I manually installed) to v0.9.8.2-146

So that looks to be it sorted.  Thanks for your help

**Comment by uwolfer** [comment]
If you also get this error, please try to following and report back if helps or not (I have received this hint by a JetBrains developer):

> "Check for update" action forces check for updates for sure and it is accessible through "Find action" or Settings->Appeaerance&Behavior->System Settings->Updates.

If it does not help, I can give you a contact at JetBrains in order to analyze this issue (and thus help other users in future). Thanks.
