### ISSUE TITLE
Expected authority at index 6: git://

### ISSUE THREAD

**Issue by cschlosser** [uwolfer/gerrit-intellij-plugin#236]
Using CLion 2016.2 and Gerrit Plugin 0.9.9.0-146 I get the following exception when trying to open the Gerrit tab.

```
Expected authority at index 6: git://
java.lang.IllegalArgumentException: Expected authority at index 6: git://
    at java.net.URI.create(URI.java:852)
    at com.urswolfer.intellij.plugin.gerrit.util.UrlUtils.createUriFromGitConfigString(UrlUtils.java:38)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectName(GerritUtil.java:408)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectNames(GerritUtil.java:393)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectQueryPart(GerritUtil.java:374)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.appendQueryStringForProject(GerritUtil.java:358)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getChangesForProject(GerritUtil.java:291)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.getChanges(GerritToolWindow.java:130)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.reloadChanges(GerritToolWindow.java:114)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.createToolWindowContent(GerritToolWindow.java:97)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindowFactory.createToolWindowContent(GerritToolWindowFactory.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:568)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$9.run(ToolWindowManagerImpl.java:550)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.net.URISyntaxException: Expected authority at index 6: git://
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.failExpecting(URI.java:2854)
    at java.net.URI$Parser.parseHierarchical(URI.java:3102)
    at java.net.URI$Parser.parse(URI.java:3053)
    at java.net.URI.<init>(URI.java:588)
    at java.net.URI.create(URI.java:850)
    ... 32 more
```

It worked for me until today when I wanted to check out the most recent Gerrit patches.

**Comment by uwolfer** [comment]
@christophschlosser: Did it work before the update with exactly the same plugin configuration? Do you remember when you have updated the plugin the last time?

**Comment by uwolfer** [comment]
@christophschlosser: Can you please look into your `.git/config file`? Are there remotes with empty urls set?

**Comment by cschlosser** [comment]
Hey,
sorry for the late reply.
It seems to be working now again without changing anything. This is really weird and annoys me more than it not working. (I'd like to keep this open for another week or so just to see if this occurs again)
There were no empty remotes in the git-config file.

**Comment by uwolfer** [comment]
Please reopen if you can reproduce this issue again.
