### ISSUE TITLE
AssertionError when using hotkey for the "Reload" button

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#242]
... I assigned a hotkey to the "Reload" Button in the gerrit toolbar. Pressing it sometimes causes this NPE.

Plugin version: 0.9.9.0-146

IntelliJ version: IntelliJ IDEA 2016.2.3 IU-162.1812.17

OS: Mac OS X 10.11.6

Java: JetBrains s.r.o 1.8.0_112-release

Exception: 

```
java.lang.AssertionError
    at com.intellij.openapi.actionSystem.AnActionEvent.getRequiredData(AnActionEvent.java:194)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.RefreshAction.actionPerformed(RefreshAction.java:46)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.RefreshAction$Proxy.actionPerformed(RefreshAction.java:60)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

(Received as exception report.)

**Comment by uwolfer** [comment]
Duplicate of #258.
