### ISSUE TITLE
Null pointer exception when opening gerrit panel on a specific project

### ISSUE THREAD

**Issue by mlazowik** [uwolfer/gerrit-intellij-plugin#247]
The fun part is that this happens only for one specific repository. Also, notifications work OK (changes waiting for review popup), but opening gerrit panel hangs the whole app. I am still able to close the window (whole window, not panel itself) without killing the app.

Looks like the error happens [here](https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/SelectedRevisions.java#L57). I suspect that the case is that `currentRevision` is `null` **and** `changeInfo.revisions` is also `null`. Or something else, I am not familiar with gerrit API. Even if it is a bug/misconfiguration on gerrit side, it should not cause exceptions here.

Plugin version: `0.9.9.1-146`

PyCharm `2016.2.3`
Build `#PY-162.1967.10`, built on September 7, 2016

```
use Optional.orNull() instead of Optional.or(null)
java.lang.NullPointerException: use Optional.orNull() instead of Optional.or(null)
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at com.google.common.base.Absent.or(Absent.java:51)
	at com.urswolfer.intellij.plugin.gerrit.SelectedRevisions.get(SelectedRevisions.java:57)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritSelectRevisionInfoColumn.valueOf(GerritSelectRevisionInfoColumn.java:71)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritSelectRevisionInfoColumn.valueOf(GerritSelectRevisionInfoColumn.java:53)
	at com.intellij.util.ui.ListTableModel.getValueAt(ListTableModel.java:111)
	at javax.swing.JTable.getValueAt(JTable.java:2717)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:162)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:141)
	at javax.swing.JTable.getRowHeight(JTable.java:992)
	at javax.swing.JTable.getCellRect(JTable.java:2937)
	at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1694)
	at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:575)
	at java.awt.Container.layout(Container.java:1510)
	at com.intellij.ui.components.JBScrollPane.layout(JBScrollPane.java:260)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at com.intellij.ide.IdeRepaintManager.validateInvalidComponents(IdeRepaintManager.java:85)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by mlazowik** [comment]
I suspect that reproducing this can be hard, so I'll try to find some time and debug this.

**Comment by uwolfer** [comment]
I get this exception report from time to time, but I have not idea how it can be reproduced. It would really help if you would find a way to reproduce it.

**Comment by mlazowik** [comment]
This fails on a change that has no `currentRevision` and empty `revisions`. Whole `ChangeInfo` object: https://pastebin.com/Y5EqC23H

No one can access the change via the web interface. Direct link (gerrit.url/1297) returns "The page you requested was not found, or you do not have permission to view this page", searching by change owner or `changeId` returns nothing.

**Comment by uwolfer** [comment]
@mlazowik: Thanks for your analysis. Does this specific change show up in the Gerrit web UI list?

**Comment by mlazowik** [comment]
Nope

> searching by change owner or changeId returns nothing.

**Comment by uwolfer** [comment]
@mlazowik: What's the version of your Gerrit server?

**Comment by mlazowik** [comment]
2.11. We should be updating soon. Hopefully.

**Comment by uwolfer** [comment]
Just to make sure that I understand it correctly: The change you are talking about is displayed in the list of changes in the IntelliJ Gerrit plugin, but it is not displayed in the web UI at the same time? This is really strange because the web UI uses the same REST API as the plugin does (at least I think this way already the case with Gerrit 2.11).

Please report back if you still can reproduce this issue after the Gerrit update.

**Comment by mlazowik** [comment]
Yep, it tries to show it and generates a lot of exceptions, the window becomes unresponsive.

Will report back after the update, thanks.

**Comment by uwolfer** [comment]
I have added a workaround which prevents broken UI. The revision column is just empty now when no revisions are available.
