### ISSUE TITLE
secret_password_lookup_sync error

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#248]
Plugin version: 0.9.9.1-146
IntelliJ version: IntelliJ IDEA 2016.3 IU-163.7743.44
OS: Linux 4.8.6-1-ARCH
Java: Oracle Corporation 1.8.0_112

```
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at com.intellij.credentialStore.SecretCredentialStore.get(linuxSecretLibrary.kt:147)
    at com.intellij.credentialStore.CredentialStoreWrapper.get(CredentialStoreWrapper.kt:52)
    at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.get(PasswordSafeImpl.kt:53)
    at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
    at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:30)
    at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:61)
    at com.urswolfer.intellij.plugin.gerrit.GerritSettings.getPassword(GerritSettings.java:131)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritUpdatesNotificationComponent.handleNotification(GerritUpdatesNotificationComponent.java:88)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritUpdatesNotificationComponent.projectOpened(GerritUpdatesNotificationComponent.java:52)
    at com.urswolfer.intellij.plugin.gerrit.ui.GerritUpdatesNotificationComponent$Proxy.projectOpened(GerritUpdatesNotificationComponent.java:174)
    at com.intellij.openapi.project.impl.ProjectImpl.b(ProjectImpl.java:387)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:69)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:422)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.f(ProjectManagerImpl.java:653)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.b(ProjectManagerImpl.java:329)
    at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:173)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:583)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:435)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:338)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:342)
    at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:321)
    at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:193)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:403)
    at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:188)
    at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:613)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:647)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:381)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:368)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:347)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
    at com.sun.proxy.$Proxy50.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:340)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
    at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:338)
    at com.intellij.idea.IdeaApplication.b(IdeaApplication.java:193)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:69)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
This issue seems to be related with IntelliJ 2016.3.

This is an IntelliJ bug, see also:
* https://youtrack.jetbrains.com/issue/IDEA-163613
* https://youtrack.jetbrains.com/issue/IDEA-160703

Possible workarounds:
* deactivate KWallet when using KDE
* install `gnome-keyring` 
* use `-Duse.linux.keychain=false` property

**Comment by StefanPenndorf** [comment]
After upgrading to 2016.3 (from IntelliJ14.1) I had this problem, too. I'm using KUbuntu with KDE. Deactivating KWallet didn't help. Using -Duse.linux.keychain=false didn't help either.
I got rid of the exception by installing gnome-keyring.

Nevertheless I had to follow @AlexJF's steps in https://github.com/uwolfer/gerrit-intellij-plugin/issues/178#issuecomment-263816867 in order to view my gerrit changes again.

Now gerrit plugin warns me that I didn't configure git on startup and shows all changes of all projects, although that option is disabled. I can work around that by fetching from gerrit via IntelliJ (I usually work at command line/terminal to do that but one needs to use the menu for that work around...). After entering the password for my ssh key and fetching from gerrit via IntelliJ the gerrit plugin recognizes the git settings and shows the correct list of changes.
That is stupid to do every morning but I don't know another way right now. Would be nice/better if gerrit plugin could trigger the authentication itself on startup.

**Comment by uwolfer** [comment]
This issue is most probably not related to this plugin. See comment above for possible workarounds.

**Comment by uwolfer** [comment]
I have received this hint from another user:
> I've changed password store to Keepass in IJ, then when prompted by Gerrit for pass I entered it and clicked OK  but still got an issue. After that I opened Keepass database made by IJ and saw the password wasn't saved so I added it manually and now everything works fine.
