### ISSUE TITLE
StackOverflowError while loading password

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#249]
Plugin version: 0.9.9.1-146
IntelliJ version: IntelliJ IDEA 2016.3 IC-163.7743.44
OS: Mac OS X 10.12.1
Java: JetBrains s.r.o 1.8.0_112-release

```
java.lang.StackOverflowError
    at com.sun.jna.Native.invokeInt(Native Method)
    at com.sun.jna.Function.invoke(Function.java:390)
    at com.sun.jna.Function.invoke(Function.java:323)
    at com.sun.jna.Library$Handler.invoke(Library.java:236)
    at com.intellij.credentialStore.$Proxy20.SecKeychainFindGenericPassword(Unknown Source)
    at com.intellij.credentialStore.MacOsKeychainLibraryKt.findGenericPassword(macOsKeychainLibrary.kt:99)
    at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:40)
    at com.intellij.credentialStore.CredentialStoreWrapper.get(CredentialStoreWrapper.kt:52)
    at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.get(PasswordSafeImpl.kt:53)
    at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
    at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:30)
    at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:61)
    at com.urswolfer.intellij.plugin.gerrit.GerritSettings.getPassword(GerritSettings.java:131)
    at com.urswolfer.intellij.plugin.gerrit.GerritSettings.isLoginAndPasswordAvailable(GerritSettings.java:146)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup.update(ReviewActionGroup.java:71)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup$Proxy.update(ReviewActionGroup.java:135)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:120)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setEnabled(DefaultButtonModel.java:209)
    at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2092)
    at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:338)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:297)
    at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:287)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:141)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:120)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setEnabled(DefaultButtonModel.java:209)
    at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2092)
    at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:338)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:297)
    at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:287)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup.update(ReviewActionGroup.java:71)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup$Proxy.update(ReviewActionGroup.java:135)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:120)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setEnabled(DefaultButtonModel.java:209)
    at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2092)
    at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:338)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:297)
    at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:287)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:141)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:120)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setEnabled(DefaultButtonModel.java:209)
    at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2092)
    at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:338)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:297)
    at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:287)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup.update(ReviewActionGroup.java:71)
    at com.urswolfer.intellij.plugin.gerrit.ui.action.ReviewActionGroup$Proxy.update(ReviewActionGroup.java:135)
...
```

Got this as exception report; I have no idea how this can be reproduced. Please post a comment when you can reproduce it.

**Comment by uwolfer** [comment]
I'm not able to reproduce this issue. Please add a comment if you can reproduce it.
