### ISSUE TITLE
AssertionError when using keyboard shortcut for refresh button

### ISSUE THREAD

**Issue by welkinbai** [uwolfer/gerrit-intellij-plugin#258]
I met exception when I pressed refresh shortcut key.
And I can not click **review** in gerrit tab.It is gray.However,I can use review in web browser when click **Open in Gerrit**
```
null
java.lang.AssertionError
	at com.intellij.openapi.actionSystem.AnActionEvent.getRequiredData(AnActionEvent.java:194)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.RefreshAction.actionPerformed(RefreshAction.java:46)
	at com.urswolfer.intellij.plugin.gerrit.ui.action.RefreshAction$Proxy.actionPerformed(RefreshAction.java:60)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:361)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:297)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
@welkinbai: Does this happen when you press a keyboard shortcut? Or does it happen when you press the button in the Gerrit toolwindow toolbar?

**Comment by welkinbai** [comment]
press a keyboard shortcut.
my keymap:
![image](https://cloud.githubusercontent.com/assets/13196370/21668127/d076ef56-d339-11e6-809d-54e3d174d22d.png)

**Comment by uwolfer** [comment]
Does it work when you press the button instead of using the keyboard shortcut?

**Comment by welkinbai** [comment]
yes,just press keyboard shortcut will meet exception. press button works well.
