### ISSUE TITLE
Unable to push

### ISSUE THREAD

**Issue by cghislai** [uwolfer/gerrit-intellij-plugin#260]
Hi,

I have a repo with the following remotes:
gerrit  http://ghislai@my.host:9090/phenix (fetch)
gerrit  http://ghislai@my.host:9090/phenix (push)
origin  ssh://ghislai@my.host:29418/phenix.git (fetch)
origin  ssh://ghislai@my.host:29418/phenix.git (push)

I configured the gerrit plugin to use  http://my.host:9090 with my credential and successfully tested the connection.
I managed to list the gerrit changes. But when I attempt to push my local branch (named _dev_gitignore) to the gerrit one (named dev), I get "Push failed. Failed with error: Could not read from remote repository", with the following lines in the idea logs:
```
2017-01-27 12:04:25,567 [1831178]   INFO -       #git4idea.repo.GitConfig - No branch.fssl.merge/rebase item in the .git/config                                                                                   
2017-01-27 12:04:25,567 [1831178]   INFO -       #git4idea.repo.GitConfig - No branch._fssl_33170.merge/rebase item in the .git/config                                                                            
2017-01-27 12:04:25,625 [1831236]   INFO -       #git4idea.repo.GitConfig - No branch.fssl.merge/rebase item in the .git/config                                                                                   
2017-01-27 12:04:25,625 [1831236]   INFO -       #git4idea.repo.GitConfig - No branch._fssl_33170.merge/rebase item in the .git/config                                                                            
2017-01-27 12:04:25,631 [1831242]   INFO -  #git4idea.commands.GitHandler - [phenix] git -c core.quotepath=false push --progress --porcelain origin refs/heads/_dev_gitignore:refs/drafts/dev --set-upstream      
2017-01-27 12:04:25,958 [1831569]   INFO -  #git4idea.commands.GitHandler - java.io.IOException: Authentication failed:                                                                                           
2017-01-27 12:04:25,958 [1831569]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.authenticate(SSHMain.java:298)                                                                  
2017-01-27 12:04:25,958 [1831569]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:172)                                                                         
2017-01-27 12:04:25,958 [1831569]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)                                                                          
2017-01-27 12:04:25,965 [1831576]   INFO -  #git4idea.commands.GitHandler - fatal: Could not read from remote repository.                                                                                         
2017-01-27 12:04:25,965 [1831576]   INFO -  #git4idea.commands.GitHandler - Please make sure you have the correct access rights                                                                                   
2017-01-27 12:04:25,965 [1831576]   INFO -  #git4idea.commands.GitHandler - and the repository exists.                                                                                                            
2017-01-27 12:04:25,986 [1831597]   INFO -  #git4idea.commands.GitHandler - [phenix] git -c core.quotepath=false push --progress --porcelain origin refs/heads/_dev_gitignore:refs/drafts/dev --set-upstream      
2017-01-27 12:04:26,301 [1831912]   INFO -  #git4idea.commands.GitHandler - java.io.IOException: Authentication failed:                                                                                           
2017-01-27 12:04:26,301 [1831912]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.authenticate(SSHMain.java:298)                                                                  
2017-01-27 12:04:26,301 [1831912]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:172)                                                                         
2017-01-27 12:04:26,301 [1831912]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)                                                                          
2017-01-27 12:04:26,318 [1831929]   INFO -  #git4idea.commands.GitHandler - fatal: Could not read from remote repository.                                                                                         
2017-01-27 12:04:26,318 [1831929]   INFO -  #git4idea.commands.GitHandler - Please make sure you have the correct access rights                                                                                   
2017-01-27 12:04:26,318 [1831929]   INFO -  #git4idea.commands.GitHandler - and the repository exists.                                                                                                            
2017-01-27 12:04:26,332 [1831943]   INFO -  #git4idea.commands.GitHandler - [phenix] git -c core.quotepath=false push --progress --porcelain origin refs/heads/_dev_gitignore:refs/drafts/dev --set-upstream      
2017-01-27 12:04:26,646 [1832257]   INFO -  #git4idea.commands.GitHandler - java.io.IOException: Authentication failed:                                                                                           
2017-01-27 12:04:26,647 [1832258]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.authenticate(SSHMain.java:298)                                                                  
2017-01-27 12:04:26,647 [1832258]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:172)                                                                         
2017-01-27 12:04:26,647 [1832258]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)                                                                          
2017-01-27 12:04:26,654 [1832265]   INFO -  #git4idea.commands.GitHandler - fatal: Could not read from remote repository.                                                                                         
2017-01-27 12:04:26,654 [1832265]   INFO -  #git4idea.commands.GitHandler - Please make sure you have the correct access rights                                                                                   
2017-01-27 12:04:26,654 [1832265]   INFO -  #git4idea.commands.GitHandler - and the repository exists.                                                                                                            
2017-01-27 12:04:26,688 [1832299]   INFO -       #git4idea.repo.GitConfig - No branch._fssl_33170.merge/rebase item in the .git/config                                                                            
2017-01-27 12:04:26,688 [1832299]   INFO -       #git4idea.repo.GitConfig - No branch.fssl.merge/rebase item in the .git/config                                                                                   
```

**Comment by uwolfer** [comment]
Are you able to push from IntelliJ when you do not use the Gerrit plugin?

**Comment by uwolfer** [comment]
@cghislai: Please answer my question above.

**Comment by stessy** [comment]
Hi Urs,

the problem has been solved by selecting the "Native" SSH executable instead of "Built-in".

Sorry for the quite late reply.

**Comment by cghislai** [comment]
Thanks @stessy .
Sorry @uwolfer , forgot about this. Thanks for this plugin works great now :)
