### ISSUE TITLE
java.lang.NullPointerException on Gerrit.Refresh

### ISSUE THREAD

**Issue by NiasSt90** [uwolfer/gerrit-intellij-plugin#271]
i (or better all my workmates) got the following NPE after select one specific review in the gerrit plugin.
After this NPE IntelliJ idea hang-up forever (runs with 100% cpu-load and must be killed). 
The NPE can be reproduced with this review on all of our platforms/JDK-versions. 
Perhaps it's a IDEA-Bug, but currently only triggered by the gerrit plugin.

```
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.3.4  Build #IU-163.12024.16 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_77 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - Last Action: Gerrit.Refresh 
2017-03-02 08:21:44,063 [58739798]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
        at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
        at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
        at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
        at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
        at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
        at javax.swing.plaf.basic.BasicTextUI$RootView.getMinimumSpan(BasicTextUI.java:1369)
        at javax.swing.plaf.basic.BasicTextUI.getMinimumSize(BasicTextUI.java:945)
        at javax.swing.JEditorPane.getScrollableTracksViewportWidth(JEditorPane.java:1461)
        at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1339)
        at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:467)
        at java.awt.Container.layout(Container.java:1510)
        at java.awt.Container.doLayout(Container.java:1499)
        at java.awt.Container.validateTree(Container.java:1695)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validateTree(Container.java:1704)
        at java.awt.Container.validate(Container.java:1630)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
        at com.intellij.ide.IdeRepaintManager.validateInvalidComponents(IdeRepaintManager.java:85)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
Can you find something special in this change? Probably extra long content or subject? The crash looks inside IntelliJ or even inside Java / Swing.

If your Gerrit server is public, please tell me how I can reproduce it.

**Comment by NiasSt90** [comment]
Am Donnerstag, 2. März 2017, 11:51:39 schrieb Urs Wolfer:
> Can you find something special in this change? Probably extra long
> content or subject? The crash looks inside IntelliJ or even inside
> Java / Swing.

not really.

> 
> If your Gerrit server is public, please tell me how I can reproduce
> it.

nope.

i've attached two screenshots of the review, one from web-ui and one 
after selecting the review in the plugin.

![gerrit_problem_review_idea](https://cloud.githubusercontent.com/assets/5861866/23556556/49775024-002d-11e7-9588-6b2f4316f2f2.png)

![gerrit_problem_review](https://cloud.githubusercontent.com/assets/5861866/23556583/5c29fe06-002d-11e7-93d0-d47da1e3dfe2.png)


Can i enable some interesting logging facilities to get more details?

regards
msc

**Comment by uwolfer** [comment]
I have really no idea what causes this exception. In your trace, there is no sign of this plugin. I think the only real way to get more information is to debug this plugin. You could find a guide how to setup a development environment in the README.

**Comment by uwolfer** [comment]
@NiasSt90: Can you still reproduce this issue?

**Comment by uwolfer** [comment]
Please report back if you can reproduce it again.
