### ISSUE TITLE
Illegal character in path

### ISSUE THREAD

**Issue by ThrashAbaddon** [uwolfer/gerrit-intellij-plugin#282]
If git repo has a space in its name the plugin crashes.

`Error msg: Illegal character in path at index 37: ssh://myUsername@gerrit.name.com:39528/SDT Framework/act`

```
Illegal character in path at index 37: ssh://myUsername@gerrit.name.com:39528/SDT Framework/act
java.lang.IllegalArgumentException: Illegal character in path at index 37: ssh://myUsername@gerrit.name.com:39528/SDT Framework/act
at java.net.URI.create(URI.java:852)
at com.urswolfer.intellij.plugin.gerrit.util.UrlUtils.createUriFromGitConfigString(UrlUtils.java:38)
at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectName(GerritUtil.java:408)
at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectNames(GerritUtil.java:393)
at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getProjectQueryPart(GerritUtil.java:374)
at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.appendQueryStringForProject(GerritUtil.java:358)
at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.getChangesForProject(GerritUtil.java:291)
at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.getChanges(GerritToolWindow.java:131)
at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.reloadChanges(GerritToolWindow.java:115)
at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindow.createToolWindowContent(GerritToolWindow.java:98)
at com.urswolfer.intellij.plugin.gerrit.ui.GerritToolWindowFactory.createToolWindowContent(GerritToolWindowFactory.java:37)
at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:568)
at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:402)
at com.intellij.openapi.wm.impl.commands.RequestFocusInToolWindowCmd.processRequestFocus(RequestFocusInToolWindowCmd.java:72)
at com.intellij.openapi.wm.impl.commands.RequestFocusInToolWindowCmd.lambda$run$0(RequestFocusInToolWindowCmd.java:60)
at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
at com.intellij.openapi.wm.impl.commands.RequestFocusInToolWindowCmd.run(RequestFocusInToolWindowCmd.java:60)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.ToolWindowsPane$AddDockedComponentCmd.run(ToolWindowsPane.java:778)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:92)
at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
at com.intellij.openapi.wm.impl.CommandProcessor.execute(CommandProcessor.java:64)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:537)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.java:694)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$MyInternalDecoratorListener.activated(ToolWindowManagerImpl.java:2292)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
at com.intellij.openapi.wm.impl.$Proxy86.activated(Unknown Source)
at com.intellij.openapi.wm.impl.InternalDecorator.fireActivated(InternalDecorator.java:244)
at com.intellij.openapi.wm.impl.StripeButton.actionPerformed(StripeButton.java:302)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.Component.processMouseEvent(Component.java:6533)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:293)
at java.awt.Component.processEvent(Component.java:6298)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.net.URISyntaxException: Illegal character in path at index 37: ssh://myUsername@gerrit.name.com:39528/SDT Framework/act
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parseHierarchical(URI.java:3105)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at java.net.URI.create(URI.java:850)
... 134 more
```

**Comment by uwolfer** [comment]
@ThrashAbaddon Can you please try to replace the space with %20? If that works, I can do this as workaround because I cannot find any nice solution.

Reference: https://stackoverflow.com/questions/4992317/illegal-character-in-path-at-index-16 (highest voted solution does not work for us because it also encodes @ in URLs for example)

**Comment by ThrashAbaddon** [comment]
@uwolfer The fix works. The repo link is `ssh://myUsername@gerrit.name.com:39528/SDT%20Framework/act`. Thank you. :)
