### ISSUE TITLE
StringIndexOutOfBoundsException on refresh

### ISSUE THREAD

**Issue by jorissaenen** [uwolfer/gerrit-intellij-plugin#285]
I often receive this exception. When I set a lot of filters before refreshing the change list, there is no exception.

Plugin version: 1.0.0.1-146
IntelliJ version: IntelliJ IDEA 2016.3.7 IU-163.15529.5
OS: Windows 7 6.1
Java: Oracle Corporation 1.8.0_112

Exception:
```
String index out of range: 9
java.lang.StringIndexOutOfBoundsException: String index out of range: 9
	at java.lang.String.substring(String.java:1963)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.getHash(GerritChangeListPanel.java:419)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.generateColumnsInfo(GerritChangeListPanel.java:253)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.initModel(GerritChangeListPanel.java:232)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel.setChanges(GerritChangeListPanel.java:216)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel$2.consume(GerritChangeListPanel.java:148)
	at com.urswolfer.intellij.plugin.gerrit.ui.GerritChangeListPanel$2.consume(GerritChangeListPanel.java:145)
	at com.urswolfer.intellij.plugin.gerrit.rest.LoadChangesProxy$1.consume(LoadChangesProxy.java:74)
	at com.urswolfer.intellij.plugin.gerrit.rest.LoadChangesProxy$1.consume(LoadChangesProxy.java:63)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20$1$1.run(GerritUtil.java:695)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by uwolfer** [comment]
@saenenjoris This exception is probably caused by one specific, probably "corrupt" change where no change-id (?) is available. Can you probably try to find the change which breaks and check how it looks in the web UI (i.e. is there a change-id available or can you see something special)?

**Comment by uwolfer** [comment]
@saenenjoris: Please answer my question above.

**Comment by jorissaenen** [comment]
I think I found the "corrupt" change:

> ServiceConnectors - Using new EBK connector in Services Connectors  
> 
> /---------------------------------------- 
> Project or Feature: ServiceConnectors 
> Target Release: Giganta 
> Impact: Connection to EBK 
>/ ----------------------------------------  
> Change-Id: If21bb6a8dad84a635d60c5d1a83b082a7d07c323
> 
I added the forward slash in this example because otherwise the layout was changing in this comment. There is no big difference with the other changes...

**Comment by uwolfer** [comment]
@saenenjoris: Thanks for your feedback.

Can you please get the JSON result of this change? This is what the plugin consumes. You can get it that way:
https://gerrit.example.com/a/changes/number (replace number with your change number (the one you see in the url - it's not the change-id). If this URL does not work, please remove the /a from the URL.

**Comment by jorissaenen** [comment]
Weird, Change-id is empty while Gerrit generated it automatically.

`)]}'
{
  "id": "EBMobile~develop~",
  "project": "EBMobile",
  "branch": "develop",
  "topic": "Giganta",
  "hashtags": [],
  "change_id": "",
  "subject": "ServiceConnectors - Using new EBK connector in Services Connectors",
  "status": "NEW",
  "created": "2017-08-10 07:23:54.562000000",
  "updated": "2017-08-11 06:41:34.757000000",
  "mergeable": true,
  "submittable": false,
  "insertions": 0,
  "deletions": 0,
  "_number": 1249,
  "owner": {
    "_account_id": 1000516
  }
}`

This issue can be closed: Thanks! :+1:

**Comment by uwolfer** [comment]
@saenenjoris: Thanks for your help. I have added a workaround so this error won't happen anymore even when a change-id is empty.
