### ISSUE TITLE
Exception "Sorry but parent: Project (Disposed) ... has already been disposed"

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#291]
Exception message: Sorry but parent: Project (Disposed) project_name has already been disposed (see the cause for stacktrace) so the child: null 24506114: running=false; canceled=false; task=null will never be disposed

Addition information: 
I had a project open. I opened an additional project window to look at its file watcher settings. After using the windows snipping tool to copy the file watcher settings I closed the additional project window. I made the desired changes to the filewatcher and added and removed empty lines to an .scss file to see whether the changes had the desired effect.

I committed the changes already made to the original project through the version control window. I then opened the gerrit window to see whether I had already merged changes made previously that day. At this point the error occured for the already closed additional project in the project I was originally working on.

_(received as exception report)_

Plugin version: 1.0.2-146
IntelliJ version: PhpStorm 2017.2.3 PS-172.4155.25
OS: Windows 10 10.0
Java: JetBrains s.r.o 1.8.0_152-release

Exception:
```
com.intellij.util.IncorrectOperationException: Sorry but parent: Project (Disposed) project_name has already been disposed (see the cause for stacktrace) so the child: null 24506114: running=false; canceled=false; task=null will never be disposed
    at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:66)
    at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
    at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
    at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:125)
    at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:84)
    at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:63)
    at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:44)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:139)
    at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:341)
    at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:325)
    at com.intellij.openapi.progress.Task.queue(Task.java:115)
    at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20.run(GerritUtil.java:707)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by James-Antrim** [comment]
Thank you.
