### ISSUE TITLE
Password is required on every refresh, after leaving IDE running overnight

### ISSUE THREAD

**Issue by fpaaske** [uwolfer/gerrit-intellij-plugin#298]
Hi!

After successfully installing and configuring the plugin in WebStorm, the plugin works as it should during that day.

The next day, if I left the IDE running, it will ask for my Gerrit password every time I click the refresh button. If I restart the IDE, it works fine again.

I couldn't find any settings that looked relevant for this issue.

Plugin version 1.0.4-146
WebStorm version 2017.2.4

Frank

**Comment by uwolfer** [comment]
@frapaa: What have you configured in WebStrom password settings? And what's the title / content of the window of the password request window?
Do you suspend the machine overnight (before the password dialog is shown)?

**Comment by fpaaske** [comment]
I know for sure it was suspended this weekend, but I'm not sure about the first incident.

WebStorm settings:
<img width="1100" alt="webstorm-settings" src="https://user-images.githubusercontent.com/1579581/32429838-c4a750ac-c2cc-11e7-8dfa-4cbf2eec7e6d.png">


I get this dialog in WebStorm:
<img width="682" alt="gerrit-password-error" src="https://user-images.githubusercontent.com/1579581/32429629-c61f332e-c2cb-11e7-85d7-926311d094a5.png">

I have tried to fill in the password, but it keeps popping up again, three times (I think) before it goes away until next time I press refresh. It's unclear if it's asking for the Gerrit password or my password to access KeyChain, but neither of them works.

Today I clicked cancel on this twice, then I got an error:
```
find: An invalid record was encountered. (-67701)
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.credentialStore.MacOsKeychainLibraryKt.a(macOsKeychainLibrary.kt:197)
	at com.intellij.credentialStore.MacOsKeychainLibraryKt.findGenericPassword(macOsKeychainLibrary.kt:101)
	at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:42)
	at com.intellij.credentialStore.CredentialStoreWrapper.get(CredentialStoreWrapper.kt:52)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.get(PasswordSafeImpl.kt:53)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:30)
	at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:61)
	at com.urswolfer.intellij.plugin.gerrit.GerritSettings.preloadPassword(GerritSettings.java:160)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20.run(GerritUtil.java:716)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```


Eventually I got an error message in the event log saying 

> Failed to get Gerrit changes.: Request not successful. Message: Bad Request. Status-Code: 400. Content: Not Signed In

Going to settings to verify (and successfully test) the settings doesn't help.


IntelliJ seems to have the same issue, but without the initial password popup dialog. I goes directly to the error message in the event log.

**Comment by uwolfer** [comment]
The dialog in your 2nd screenshot is shown by Gerrit and you should enter the Gerrit password there.

Can you please tell me how your WebStorm / IntelliJ password settings look like (Appearance and Behavior -> System Settings -> Passwords)?

**Comment by fpaaske** [comment]
Entering the gerrit password in that dialog doesn't work, it just keeps popping up. The password settings is set to Save passwords -> In native Keychain.

**Comment by uwolfer** [comment]
Hmm, I do not really have an idea here and cannot test on macOS. But it is possible that it is related to the native keychain setting. Probably the keychain gets locked after some time of inactivity? You could try one of the other password save options in IntelliJ and see if the same thin happens.

**Comment by fpaaske** [comment]
I think this have been fixed in one of your latest releases. At least I'm not experiencing this anymore.

**Comment by uwolfer** [comment]
Thanks for your feedback.

**Comment by delphikettle** [comment]
Actually I'm experiencing same bug now on latest version of the plugin

**Comment by uwolfer** [comment]
@delphikettle: Have you tried to change IntelliJ password safe settings? I know some users who have changed it and fixed issues like this.

**Comment by delphikettle** [comment]
@uwolfer It was set to "in native Keychain", then I've changed it to "In KeePass" and bug has gone. Thanks
