### ISSUE TITLE
Plugin failed to initialize

### ISSUE THREAD

**Issue by AlehandroRamosRodrigues** [uwolfer/gerrit-intellij-plugin#304]
I have installed gerrit-intellij-plugin-1.0.4-146 on PyCharm Community 2017.3.2, but after PyCharm re-start I got following error

```
Plugin 'com.urswolfer.intellij.plugin.gerrit' failed to initialize and will be disabled.  Please restart PyCharm.

java.lang.NoClassDefFoundError: com/google/inject/AbstractModule
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:276)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:272)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:241)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:142)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.urswolfer.intellij.plugin.gerrit.push.GerritPushExtension$Proxy.<init>(GerritPushExtension.java:134)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:474)

```

**Comment by uwolfer** [comment]
@AlehandroRamosRodrigues: Can you please uninstall and install again (I have recently released 1.0.5)? It looks like your plugin installation is broken.

Did it ever work before?

**Comment by AlehandroRamosRodrigues** [comment]
It seem to work if to install as zip while I was trying to extract folder and install gerrit-intellij-plugin-1.0.4-146.jar file... Now it's ok

**Comment by uwolfer** [comment]
Thanks for your feedback. Yes, the plugin only works when you install the original ZIP file. The best way to install the plugin in order to also get updates is to use the plugin manager in IntelliJ / PyCharm settings.
