### ISSUE TITLE
Plugin error for Gerrit on IntelliJ

### ISSUE THREAD

**Issue by bpendharkar** [uwolfer/gerrit-intellij-plugin#316]
Hello, 

I recently added the Gerrit Plugin (gerrit-intellij-plugin-1.0.6-146.jar) to IntelliJ and attempted to restart it. I got the following error  (I can paste the entire stack trace if needed) : 

Plugin 'com.urswolfer.intellij.plugin.gerrit' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/google/inject/AbstractModule
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:278)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:274)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:243)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:142)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.urswolfer.intellij.plugin.gerrit.push.GerritPushExtension$Proxy.<init>

**Java** : 
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

I'd appreciate any response on how to resolve this.

**Comment by uwolfer** [comment]
@bpendharkar: Have you installed the plugin with IntelliJ plugin manager? If not: make sure that you install the ZIP file, not only the jar. See also: #304.

**Comment by bpendharkar** [comment]
Thanks @uwolfer !
