### ISSUE TITLE
IllegalArgumentException: expected one element but was

### ISSUE THREAD

**Issue by mvaal** [uwolfer/gerrit-intellij-plugin#318]
We recently upgrade to Gerrit 2.14.7.  I have now started getting the below error message when trying to checkout a review where another review has it as its parent.
`
expected one element but was: <com.google.gerrit.extensions.common.ChangeInfo@1f55ec27, com.google.gerrit.extensions.common.ChangeInfo@30da2ee2>
java.lang.IllegalArgumentException: expected one element but was: <com.google.gerrit.extensions.common.ChangeInfo@1f55ec27, com.google.gerrit.extensions.common.ChangeInfo@30da2ee2>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:322)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:263)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangeApiRestClient.get(ChangeApiRestClient.java:259)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$14.get(GerritUtil.java:453)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$14.get(GerritUtil.java:442)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20$1.run(GerritUtil.java:699)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Seems like somehow the options in GerritUtil.getChangeDetails are also providing child sets?

**Comment by uwolfer** [comment]
I think this happens because the search returns two changes when we expect one only. Can you break down this issue to a specific change? Probably a change which has been cherry picked to different branches?

**Comment by mvaal** [comment]
Not sure what happened here, but I am unable to recreate the issue after I submitted the problematic review.  I think you can close this, thanks.

**Comment by uwolfer** [comment]
I have an idea what could probably cause this issue: for some operations, I fetch change details by change number. The query returns more than one result when I expect details for exactly one.

@mvaal: Can you please try the following: take the number of the change which failed (you can see it in the web UI URL when you open the change) and search for it in the web UI search (just enter the number in the search field). I expect that this returns more than one result. Then try prefixing the search query with change:, e.g. "change:1234". That should return (hopefully) one result.

**Comment by mvaal** [comment]
Hey @uwolfer.  I ran into it again today with a different review.  I tried the steps above, but the search is only returning 1 review without the "change" prefix.

Sorry, I am not sure how to go about debugging this. One thing that would help would be to update the error message from the ChangeApiRestClient to show the ChangeInfo ID instead of the class toString so I could see the two changes being returned.

Other than that, I have only started seeing this with the change to 2.14.7 and it is another change where there are other non-commited changes as it's parent.

**Comment by uwolfer** [comment]
@mvaal Thanks for your feedback. Does this only happen when you check out a change? Are the details for a change displayed for example (below the list of changes)?

Anyway, I think I have found at least one thing which could be improved. Then the error message should be at least clearer if it does not fix the issue. The REST client does not use the "optimal" endpoint for getting change details (it uses the query endpoint instead of the the change-detail endpoint).

**Comment by goelvasudha** [comment]
@uwolfer I tried to follow your debugging instructions, but the search only returned 1 result without "change:" prefix. This issue seems isolated only to 1 particular change; for some reason even the info for that change doesn't get displayed on the gerrit plugin UI, I'm guessing the error interrupts that. The only thing different about this one is that it used to be a draft before it was published.

**Comment by uwolfer** [comment]
@goelvasudha Thanks for your feedback.

I have implemented a change which hopefully fixes this issue: https://github.com/uwolfer/gerrit-rest-java-client/commit/b730f02728925bbb3d8bc82d42cda68a36bcdbb2

@mvaal / @goelvasudha: If you find a few minutes, it would really help if you could try my fix with your setup und confirm whether it fixes your issues. You can download a snapshot from JitPack: https://jitpack.io/com/github/uwolfer/gerrit-rest-java-client/e0209a5b08/gerrit-rest-java-client-e0209a5b08.jar
Then you can replace the existing `gerrit-rest-java-client-0.8.13.jar` in `<intellij config dir>/config/plugins/gerrit-intellij-plugin/` and restart IntelliJ.

**Comment by goelvasudha** [comment]
@uwolfer I did try that and it seems to solve my problem, though i haven't tried with different repositories.
Thanks for your help!

**Comment by uwolfer** [comment]
I have published a new release. You can update it in IntelliJ plugin manager.
