### ISSUE TITLE
Failed to inject Gerrit push UI: javassist.CannotCompileException: [source error] cannot find constructor

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#361]
This change breaks Javassist reflection magic: https://github.com/JetBrains/intellij-community/commit/1ab27885afa82e46eba4715829c88f0de494b652

Plugin version: 1.1.2-146
IntelliJ version: IntelliJ IDEA 2019.3 IU-193.2956.37
OS: Mac OS X 10.11.6
Java: JetBrains s.r.o 11.0.4

```
javassist.CannotCompileException: [source error] cannot find constructor com.urswolfer.intellij.plugin.gerrit.push.GerritPushTargetPanel(git4idea.push.GitPushSupport,git4idea.repo.GitRepository,git4idea.push.GitPushSource,com.urswolfer.intellij.plugin.gerrit.push.GerritPushOptionsPanel)
    at javassist.CtBehavior.setBody(CtBehavior.java:474)
    at javassist.CtBehavior.setBody(CtBehavior.java:440)
    at com.urswolfer.intellij.plugin.gerrit.push.GerritPushExtension.modifyGitBranchPanel(GerritPushExtension.java:84)
    at com.urswolfer.intellij.plugin.gerrit.push.GerritPushExtension.initComponent(GerritPushExtension.java:57)
    at com.urswolfer.intellij.plugin.gerrit.push.GerritPushExtension$Proxy.initComponent(GerritPushExtension.java:139)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:41)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:91)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:70)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:200)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$4(ApplicationImpl.java:361)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:361)
    at com.intellij.idea.ApplicationLoader$startApp$5$1.run(ApplicationLoader.kt:173)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:443)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: compile error: cannot find constructor com.urswolfer.intellij.plugin.gerrit.push.GerritPushTargetPanel(git4idea.push.GitPushSupport,git4idea.repo.GitRepository,git4idea.push.GitPushSource,com.urswolfer.intellij.plugin.gerrit.push.GerritPushOptionsPanel)
    at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777)
    at javassist.compiler.TypeChecker.atNewExpr(TypeChecker.java:171)
    at javassist.compiler.ast.NewExpr.accept(NewExpr.java:75)
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
    at javassist.compiler.CodeGen.compileExpr(CodeGen.java:253)
    at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:641)
    at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:443)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:393)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
    at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
    at javassist.compiler.Javac.compileBody(Javac.java:228)
    at javassist.CtBehavior.setBody(CtBehavior.java:466)
    ... 30 more
```

**Comment by uwolfer** [comment]
Also created an issue in Jetbrains issue tracker: https://youtrack.jetbrains.com/issue/IDEA-222817

**Comment by uwolfer** [comment]
As a workaround, you can downgrade to the most recent non-EAP version of IntelliJ.

**Comment by singalen** [comment]
If the plugin needs to run with both old and new versions of IDE, maybe it can test for both method signatures? AFAIU, it uses reflection to call the method anyway.

**Comment by uwolfer** [comment]
@singalen I'd like to do that, but I've not found an easy way yet.

1) https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/push/GerritPushExtension.java#L86

2) GerritPushTargetPanel gets constructed

3) The super ctor has called here has a changed signature: https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/push/GerritPushTargetPanel.java#L39

If you see a good way, please let me know. I'd like to support both old and new IntelliJ versions without creating a new branch.

**Comment by singalen** [comment]
If you ask me, when you get `CtMethod createTargetPanelMethod = gitPushSupportClass.getDeclaredMethod("createTargetPanel")`, test it for an argument count. Simplest thing that may work (for the time being) is to compare `CtMethod.getLongName()` with the old and new values.
Then, maybe you can substitute `new com.urswolfer.intellij.plugin.gerrit.push.GerritPushTargetPanel()` with conditional call to one of two different constructors. Not sure that it's possible to load a class with two incompatible `super()` calls in two different constructors; it might allow it still.
If not, you would have to resort to two different implementations of `GerritPushTargetPanel` that only differ by their constructors. IIRC, the classloader will only load the one you refer to. In order not to duplicate code between classes, I would make them inherit a common implementation and only provide the necessary constructors.

**Comment by uwolfer** [comment]
@singalen Thanks!

First part sounds good, will try that.

About the 2nd part (different ctors in old and new IntelliJ): `GerritPushTargetPanel` is not implemented via reflection. So if I'd add two ctors with the different signatures, it would fail to compile with one of the two super calls (either the new or old, depending on which IntelliJ is used to compile against). Or do I miss something here?

**Comment by singalen** [comment]
No, that was my silly mistake. Right, one has to compile it first. To do this, one has to do some weird ritual editing or substituting the base class' code, or compile two `.class` files with the old and the new IDEA SDKs...
I don't know, is it possible to use reflection to call `super()`? Need to test it.

**Comment by singalen** [comment]
Another idea: can you replace the body of `GerritPushTargetPanel()` constructor with `setBody()`?

**Comment by uwolfer** [comment]
> Another idea: can you replace the body of `GerritPushTargetPanel()` constructor with `setBody()`?

It might be possible to add a 2nd ctor for `GerritPushTargetPanel` via reflection (javassist) in GerritPushExtension. But things get really hairy :(

I had no success when I've tried changing it in a few minutes - "writing" such javassist code is really try-and-error and I do not have much time available these days.

If somebody finds the time to try it, it would be great!

**Comment by uwolfer** [comment]
@singalen Thanks for your help - it was easier than I've expected! :)

**Comment by uwolfer** [comment]
https://github.com/uwolfer/gerrit-intellij-plugin/commit/0e45c7a9a358be0fc05129f34f45948e87722005

**Comment by uwolfer** [comment]
Fix released. Please update your plugin.

If you would like to support an official API for injecting this push dialog extension, please vote for this request: https://youtrack.jetbrains.com/issue/IDEA-136937
