### ISSUE TITLE
IllegalStateException: @NotNull method com/intellij/ui/popup/AbstractPopup.getContent must not return null

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#363]
Plugin version: 1.1.2.1-146
IntelliJ version: IntelliJ IDEA 2019.2.3 IU-192.6817.4
OS: Linux 5.0.0-27-generic
Java: JetBrains s.r.o 11.0.4

Exception:
```
java.lang.IllegalStateException: @NotNull method com/intellij/ui/popup/AbstractPopup.getContent must not return null
    at com.intellij.ui.popup.AbstractPopup.$$$reportNull$$$0(AbstractPopup.java)
    at com.intellij.ui.popup.AbstractPopup.getContent(AbstractPopup.java:1294)
    at com.urswolfer.intellij.plugin.gerrit.ui.filter.AbstractUserFilter$UserPopupAction$2.actionPerformed(AbstractUserFilter.java:115)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
    at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
    at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
    at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
    at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1428)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
    at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:222)
    at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:174)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
    at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1424)
    at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
    at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:318)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:278)
    at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
    at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
    at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
    at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
    at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
    at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
    at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
    at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
    at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
    at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
    at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:453)
    at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:407)
    at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:298)
    at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
    at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
    at java.desktop/java.awt.Component.processEvent(Component.java:6416)
    at java.desktop/java.awt.Container.processEvent(Container.java:2263)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by uwolfer** [comment]
Not able to reproduce it yet; received this feedback from an user:

> I just type a name and press CTRL+enter.
> The first time it works fine, but when I click on Select the second time, the error popup shows up and it won't work until I close and restart IDEA.

**Comment by smokey42** [comment]
I just tried to reproduce it that way and it crashed with the above exception on the second use of the "Select..." menu item in the "Owner" drop down.

**Comment by uwolfer** [comment]
@smokey42 Thanks for your feedback. Fix will be included in next release.
