### ISSUE TITLE
`GitHistoryUtils.history` is called from the EDT, leading to an assertion error

### ISSUE THREAD

**Issue by juliabeliaeva** [uwolfer/gerrit-intellij-plugin#376]
```
java.lang.Throwable: Assertion failed
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:182)
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:191)
    at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:109)
    at org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:69)
    at git4idea.commands.GitHandlerAuthenticationManager.prepareHttpAuth(GitHandlerAuthenticationManager.java:106)
    at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:67)
    at git4idea.GitUtil.tryRunOrClose(GitUtil.java:977)
    at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:66)
    at git4idea.commands.GitImplBase.run(GitImplBase.java:153)
    at git4idea.commands.GitImplBase.runCommandWithoutCollectingOutput(GitImplBase.java:92)
    at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:95)
    at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:79)
    at git4idea.history.GitDetailsCollector.readFullDetails(GitDetailsCollector.kt:32)
    at git4idea.history.GitLogUtil.readFullDetails(GitLogUtil.java:210)
    at git4idea.history.GitHistoryUtils.history(GitHistoryUtils.java:144)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.getCommit(RepositoryChangesBrowserProvider.java:225)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.access$1000(RepositoryChangesBrowserProvider.java:110)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:191)
    at com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser$4.call(RepositoryChangesBrowserProvider.java:184)
    at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:114)
    at com.urswolfer.intellij.plugin.gerrit.git.RevisionFetcher$FetchCallback.call(RevisionFetcher.java:99)
    at com.urswolfer.intellij.plugin.gerrit.git.GerritGitUtil$1.onSuccess(GerritGitUtil.java:153)
    at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:516)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$1(CoreProgressManager.java:435)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:467)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:443)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:420)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:713)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by uwolfer** [comment]
@juliabeliaeva: Do you have any information about the IntelliJ which is used when this happens?

**Comment by juliabeliaeva** [comment]
> Do you have any information about the IntelliJ which is used when this happens?

I've got reports from AppCode 201.5259.17 and IntelliJ IDEA 201.4865.12

**Comment by uwolfer** [comment]
@juliabeliaeva: Issue #399 seems to be be the same issue, which affects quite a lot of people. Do you or your team have any idea what I'm doing wrong here?
