### ISSUE TITLE
latest intellij eap breaks gerrit plugin

### ISSUE THREAD

**Issue by eekboom** [uwolfer/gerrit-intellij-plugin#412]
IU-212.3724.25 gives

```
Plugin 'com.urswolfer.intellij.plugin.gerrit' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/intellij/openapi/vcs/changes/committed/RepositoryChangesBrowser
    at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
    at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
    at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
    at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:100)
    at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:661)
    at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:51)
    at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:35)
    at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:42)
    at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
    at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
    at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:93)
    at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:56)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:187)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:99)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at com.urswolfer.intellij.plugin.gerrit.GerritModule$1.get(GerritModule.java:49)
    at com.urswolfer.intellij.plugin.gerrit.GerritModule$1.get(GerritModule.java:46)
```

**Comment by uwolfer** [comment]
Thanks for reporting this. I've already a fix ready for this, just need to release a new build for the new IJ version which breaks backwards compatibility.

**Comment by uwolfer** [comment]
Fix will be included in next release.
