### ISSUE TITLE
error logging in

### ISSUE THREAD

**Issue by eprst** [uwolfer/gerrit-intellij-plugin#432]
similar to [264](https://github.com/uwolfer/gerrit-intellij-plugin/issues/264), but I triple checked my url, it points to the main gerrit page and uses https.

Gerrit 3.1.2, plugin 1.2.5-203

```
Caused by: com.google.gerrit.extensions.restapi.RestApiException: Expected JSON but got 'text/html; charset=utf-8'.
	at com.google.gerrit.extensions.restapi.RestApiException.wrap(RestApiException.java:25)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkContentType(GerritRestClient.java:521)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:156)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.getRequest(GerritRestClient.java:118)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.get(ChangesRestClient.java:130)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.access$000(ChangesRestClient.java:37)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient$1.get(ChangesRestClient.java:95)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil.testConnection(GerritUtil.java:584)
```

**Comment by uwolfer** [comment]
@eprst Have you also checked out #422?

**Comment by eprst** [comment]
that one was about mixing up http/https as I understand. I see `https` both in the browser and plugin config.

Is there any way to see the text/html response payload?

**Comment by uwolfer** [comment]
Added some more logging information, will be available with in the next release:
https://github.com/uwolfer/gerrit-rest-java-client/commit/1e1489a703144cf5d6937b568e716180b06cf649
