### ISSUE TITLE
IDEA 2024.1: `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by changshunxu520** [uwolfer/gerrit-intellij-plugin#510]
**Here is the error message:**
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.urswolfer.intellij.plugin.gerrit.ui.filter.ShowWIPFilter$ShowWIPActionFilter' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.urswolfer.intellij.plugin.gerrit]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by uwolfer** [comment]
Another issue related to IDEA 2024.1: 

```
Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:120)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:94)
	at com.urswolfer.intellij.plugin.gerrit.GerritSettings.preloadPassword(GerritSettings.java:163)
	at com.urswolfer.intellij.plugin.gerrit.rest.GerritUtil$20.run(GerritUtil.java:724)
```

**Comment by changshunxu520** [comment]
Hello, when do you plan to release a new version?

**Comment by uwolfer** [comment]
@changshunxu520: I have released a version which contains a fix for the issue you reported. Please update the plugin to v1.3.0.
